### ISSUE TITLE
goto

### ISSUE THREAD

**Issue by Chris-Johnston** [dsdude123/GroovyRP#1]
This speaks for itself, really.

https://github.com/dsdude123/GroovyRP/blob/20318fcf0d2d24d7b91ea3627fec8dac52ef32eb/GroovyRP/Program.cs#L40

https://github.com/dsdude123/GroovyRP/blob/20318fcf0d2d24d7b91ea3627fec8dac52ef32eb/GroovyRP/Program.cs#L72

https://github.com/dsdude123/GroovyRP/blob/20318fcf0d2d24d7b91ea3627fec8dac52ef32eb/GroovyRP/Program.cs#L117

**Comment by dsdude123** [comment]
Resolved by 02b6ec5
