### ISSUE TITLE
Unable to handle Unicode charcters

### ISSUE THREAD

**Issue by Qiangong2** [dsdude123/GroovyRP#10]
The latest release from the releases page does not show Chinese Characters in Discord. I'm assuming this extends to all Unicode characters in general.

**Comment by dsdude123** [comment]
@Qiangong2 Sorry for only just now taking a look at this issue. I am having some troubles replicating this issue on my machine, could you send a sample file that causes this issue and a copy of the files.csv document generated by GroovyRP to csmediaseattle@gmail.com please? Thanks.

**Comment by Qiangong2** [comment]
@dsdude123 Oh, sorry. I forgot I had opened this issue. I found out that the issue was with my Windows install itself. Reinstalling windows fixed the issue.
