### ISSUE TITLE
Feature Request: Auto launch with Groove and System Tray mode.

### ISSUE THREAD

**Issue by Javonski** [dsdude123/GroovyRP#12]
Is it possible for it to automatically open when I open Groove? And having it minimized to system tray. I think it would be pretty cool.

**Comment by jojo2357** [comment]
It is indeed possible. I implemented it using Task Scheduler to run the program when Groove is created. To set this up, I suggest you look at the [improvements I made](https://github.com/jojo2357/Music-Discord-Presence).

**Comment by dsdude123** [comment]
This functionality is planned to be released soon.

**Comment by tameTNT** [comment]
> Is it possible for it to automatically open when I open Groove? And having it minimized to system tray. I think it would be pretty cool.

> This functionality is planned to be released soon.

While you're waiting @Javonski , this is actually pretty easy to accomplish within Windows itself using Task Scheduler:
- https://superuser.com/questions/745318/how-to-start-a-program-when-another-one-is-started

The path to Groove Music you need is `C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe` (which you can also find yourself by following the steps in the linked post and then just finding an entry for Groove Music in Event Viewer).

If you want Groovy to start minimised automatically then, during the _Start a Program_ bit while setting up the task, put `cmd` as the **Command** and then `/c start "GroovyRP" /min "path\to\groovy\executable"` for **Arguments**.

Hope that helps!

**Comment by tameTNT** [comment]
Just realised you said minimised to _system tray_. My method only minimises to the _task bar_ - I don't know how to hide it to the tray at the moment I'm afraid. 😂 Hopefully this can pull you over until then though.

**Comment by jojo2357** [comment]
either way you can script it going to the taskbar without having to open task scheduler
