### ISSUE TITLE
Picture of albums/songs?

### ISSUE THREAD

**Issue by Halfs2020** [dsdude123/GroovyRP#15]
Is it possible show the cover art for songs/albums that you're playing? Thank you for making this btw.

**Comment by jojo2357** [comment]
See #9 . You can, but not very well, you would have to [make your own discord rich presence](https://discord.com/developers/applications) and upload the images there.

**Comment by Halfs2020** [comment]
Okay, Thank you for Groovy RP and for replying fast :)

**Comment by jojo2357** [comment]
I'm not the author of GroovyRP, but i did make my own version of it that sort of does it what you want, I just haven't gotten around to fully implementing it.

**Comment by Halfs2020** [comment]
If you finish it, could please send me. That'd be incredible. Thank you

**Comment by jojo2357** [comment]
My [latest release](https://github.com/jojo2357/Music-Discord-Rich-Presence/releases/tag/1.3.1) does this as good as discord will allow.

**Comment by Halfs2020** [comment]
I've tried it but it doesn't work? all lowercase on the picture? it shows everything but the picture

**Comment by jojo2357** [comment]
can you start a discussion in my repo and we can talk more in depth there
