### ISSUE TITLE
I don't know how to install this :(

### ISSUE THREAD

**Issue by SrErikP** [dsdude123/GroovyRP#2]
How i install this? I'm new to C++ :/ help

**Comment by dsdude123** [comment]
Latest release can be downloaded here: [https://github.com/dsdude123/GroovyRP/releases/latest](https://github.com/dsdude123/GroovyRP/releases/latest)

Usage is simple, just extract the ZIP somewhere and run GroovyRP.exe. Administrator privileges are required.

Also side not nothing here is C++, all C# code.
