### ISSUE TITLE
GroovyRP doesn´t works with Windows 11's new Media Player

### ISSUE THREAD

**Issue by aquirozc** [dsdude123/GroovyRP#29]
Microsoft has recently introduced a brand-new Media player for Windows 11, intended to replace Groove Music (Microsoft.ZuneMusic) and Movies&Tv (Microsoft.ZuneVideo). As expected it is not compatible with the GroovyRP plugin.

**Comment by non-one-c** [comment]
Yeah even Windows 10 updated to the new Media Player. Would love to see an update for that.
