### ISSUE TITLE
I downloaded the latest release, but...

### ISSUE THREAD

**Issue by SrErikP** [dsdude123/GroovyRP#3]
It gives me this error right after opening it, and giving it administrator rights... Groove Music is open and with music.

![SharedScreenshot](https://user-images.githubusercontent.com/50298335/88348219-20853c80-cd4d-11ea-8d03-ae2d92c10226.jpg)

**Comment by dsdude123** [comment]
I am unable to replicate this issue on my test environment, it might be something specific to your configuration when OpenedFilesView is trying to get what files Groove Music has open.  Can you please check to see if GroovyRP has generated a files.csv file and email it to csmediaseattle@gmail.com so I can investigate this issue further? Thanks.

**Comment by SrErikP** [comment]
Yep, i sending it now

**Comment by dsdude123** [comment]
Fixed by 1b94e25095b1bc0a6f49246cd70523da3653e9ae

Download new release: [https://github.com/dsdude123/GroovyRP/releases/tag/v1.0-alpha-2](https://github.com/dsdude123/GroovyRP/releases/tag/v1.0-alpha-2)
