### ISSUE TITLE
Console application doesn't display some characters correctly

### ISSUE THREAD

**Issue by dsdude123** [dsdude123/GroovyRP#4]
Some characters (particularly Japanese characters) do not display correctly in the console. Need to investigate whether this is an issue with the console itself or with GroovyRP. Characters render properly in Discord.

![image](https://user-images.githubusercontent.com/14354266/88465047-7bfe1a00-ce74-11ea-8747-561f09d4581a.png)

![image](https://user-images.githubusercontent.com/14354266/88465052-815b6480-ce74-11ea-9bf5-4e99d29ac800.png)

**Comment by Qiangong2** [comment]
Opened #10 as well as it's unable to recognize Chinese characters. It doesn't even push them to discord, just blanks it out as "Unknown Title" Maybe it has something to do with 16 bit characters not working?
