### ISSUE TITLE
Can you please include a readme file?

### ISSUE THREAD

**Issue by IIRobotNinjaII** [dsdude123/GroovyRP#7]
Well could you try and create a readme files in order to use this?

**Comment by Megas97** [comment]
Agree, no idea how to use this at all yet it's the thing I've been looking for.

**Comment by dsdude123** [comment]
Releases page has the bare minimum instructions for this. It really is just running the program as administrator while you are using Groove Music and Discord. https://github.com/dsdude123/GroovyRP/releases

Will work on providing proper documentation sometime.

**Comment by Megas97** [comment]
I think you should just put the instructions from the Releases page as a README here and possibly a link to the Releases page so people know where to go. I think the Releases page is a bit hidden there to the side and some people maybe don't see it and there's no README as in other repos so they're kind of lost.
