### ISSUE TITLE
Error 32 message

### ISSUE THREAD

**Issue by Megas97** [dsdude123/GroovyRP#8]
Hello, this is exactly what I'm looking for but after I Build the solution as a Release and run the .exe file I get the following error:
Error 32: The process cannot access the file because it is being used by another process.
Same message appears even if I run it in Debug mode in VS. Also I run it only once so it's not like I've started multiple instances.

Also another thing is that the media information doesn't seem to update when songs change until I click the "OK" button on this Error 32 popup. When I click it it updates the info and the same popup error window appears again.

This is what I get: https://i.imgur.com/Mmyekno.png

How can I fix this?

PS: It now shows the Album artist as Artist when it should show the Contributing artists field instead. Something Groove itself does as well which is a fail xd

**Comment by dsdude123** [comment]
Sounds like something might be going wrong with handles on the output file from OpenedFilesView. I will look into this. You may consider trying one of the already compiled builds at https://github.com/dsdude123/GroovyRP/releases

**Comment by Megas97** [comment]
Seems to work fine from the Releases page, thanks.

**Comment by jojo2357** [comment]
See #13
